### ISSUE TITLE
Cannot resolve dependency when using Gradle v6.0+

### ISSUE THREAD

**Issue by 0ffz** [DRE2N/HeadLib#5]
When my project is using Gradle version 6.0 or 6.0.1 the following message is brinted when importing the project: `Could not resolve: de.erethon:headlib:3.0.2`. Same thing gets printed if I use a nonexistent dependency.

Downgrading to 5.6.4 fixes the issue. I'm not too sure what's changed between the versions, or whether it's up to Gradle themselves to fix, but all my other dependencies are working fine. Just a heads up!

**Comment by Sataniel98** [comment]
Thank you for the report. I have no idea about this because I am more used to Maven. Perhaps I made a mistake setting up the repo that Gradle 6 isn't as forgiving of as earlier versions and Maven? I'll have a look at it.

**Comment by Sataniel98** [comment]
Could you please show your build.gralde?

**Comment by 0ffz** [comment]
[Here's](https://github.com/MineInAbyss/MineInAbyss/blob/core-gameplay/build.gradle) my build.gradle.

I can try making a brand new project over the weekend and seeing whether I have the same issue there.

**Comment by Sataniel98** [comment]
Should (hopefully) work now.
