### ISSUE TITLE
[BUG] Skulls shown as Steve head

### ISSUE THREAD

**Issue by LoneDev6** [DRE2N/HeadLib#6]
Server: Spigot and Paper 1.16.1
Version: 3.0.3

Seems spigot is cleaning up the custom texture NBT data from the itemstack right after using this method:
https://github.com/DRE2N/HeadLib/blob/954e74857a3310d3f74d7e38fa00a2f691f5aa30/craftbukkit_1_16_R1/src/main/java/de/erethon/headlib/v1_16_R1.java#L67

**Comment by LoneDev6** [comment]
Found out the cause: https://hub.spigotmc.org/jira/browse/SPIGOT-5892
Just do this:
```Java
 @Override
    public NBTTagCompound createOwnerCompound(String id, String textureValue) {
        NBTTagCompound skullOwner = new NBTTagCompound();
        skullOwner.a("Id", UUID.fromString(id));
```

**Comment by Sataniel98** [comment]
I see. Thank you for letting me know.

**Comment by LoneDev6** [comment]
https://github.com/DRE2N/HeadLib/pull/7
